### ISSUE TITLE
issue about the precision

### ISSUE THREAD

**Issue by ASONG0506** [erikguo/yolov3#14]
Hi, erikguo,Thanks for your excellent job!
I trained the yolov3-spp model on coco dataset, but got really bad performance, whose precision is really low but the recall is very high. One sample of test result is shown below.
![image](https://user-images.githubusercontent.com/26050577/67259953-4e420a00-f4cb-11e9-8dd8-c3527cddcead.png)
I referenced some issue such as [#2](https://github.com/ultralytics/yolov3/issues/2) , [#295](https://github.com/ultralytics/yolov3/issues/295) , [#188](https://github.com/ultralytics/yolov3/issues/188) and [#71](https://github.com/ultralytics/yolov3/issues/71), and I modify the  hypermeter "iou_t" but the mAP drop a lot, so did you trained the model in public dataset such as coco? How can you balance betweem the precision and recall? Thank you!

**Comment by zihaozhang9** [comment]
Hello! How can I use the train.py code? I am now receiving the following error: 
`AssertionError: No labels found. Recommend correcting image and label paths.`

What are the input parameters of train.py?

**Comment by ASONG0506** [comment]
obviously you need to check your dataset



---Original---

**Comment by ASONG0506** [comment]
Finally I solved this problem by using "--evolve " in the training process to find out the best heper-parameters.

**Comment by MuhammadAsadJaved** [comment]
> Hello! How can I use the train.py code? I am now receiving the following error:
> `AssertionError: No labels found. Recommend correcting image and label paths.`
> 
> What are the input parameters of train.py?

Have you resolved your problem? 
if no then show me your train.lists and val.lists

**Comment by marmikp** [comment]
I am training in yolov3.weights model with my own single class data. F1 score increased to 0.88 in the first 50 epochs but now it is constant for all the next epochs with e-5 learning rate.
